### PR TITLE
Enhanced Contact page[advanced]

### LINKED ISSUE #88: Enhance Contact Section
Add icons Customize it

### PR DESCRIPTION
**Pull request by arjunpandey2003**
Fixes #88 
Added Icons 
Changed CSS a bit
Also removed a border-bottom from all tags.
screen shot: 
screen shot 2018-01-02 at 7 05 10 pm

Deploy Link:
https://arjunpandey2003.github.io/2014.arjunpcfossasia.org/

### CODE REVIEW

**Comment by harshit98** [comment]
@arjunpandey2003 Squash your commits. PR looks good to me!

**Comment by arjunpandey2003** [comment]
Ok

**Review by harshit98 — APPROVED** [review]
LGTM! 💯 

Good work @arjunpandey2003. The PR will be merged after Travis CI passes.

**Comment by arjunpandey2003** [comment]
Sure

**Pull request merged**
