### PR TITLE
Added a top menu bar 

### PR DESCRIPTION
**Pull request by samyakbvs**
Made it similar to the fossasia standard 
#17

### CODE REVIEW

**Comment by samyakbvs** [comment]
screen shot 2017-12-20 at 1 11 52 pm]

A screenshot of how it looks now

**Comment by akshatnitd** [comment]
@samyakbvs Please send us a demo link

**Comment by samyakbvs** [comment]
I can't rn bcs I have another PR from the current forked repo and I delted the repo which had the navbar 
So pls hang this issue for now will work on it in sometime but pls don't close it

**Comment by samyakbvs** [comment]
@akshatnitd  Till then 
You can review this - https://github.com/fossasia/2014.fossasia.org/pull/37

**Pull request closed without merging**
