### PR TITLE
Fixes #131 : Added icons and linked them in the footer

### LINKED ISSUE #131: The footer needs more social links

### PR DESCRIPTION
**Pull request by saarthakchats**
https://saarthakchats.github.io/2014.fossasia.org/

Fixes #131

### CODE REVIEW

**Comment by codedsun** [comment]
@saarthakchats Your deployed link still not show the links?

**Comment by saarthakchats** [comment]
https://saarthakchats.github.io/2014.fossasia.org/

**Comment by saarthakchats** [comment]
@codedsun

**Comment by codedsun** [comment]
@saarthakchats The link to pinterest is not working, kindly do check it

**Comment by saarthakchats** [comment]
@codedsun 
Fixed it

**Review by rupav — APPROVED** [review]
LGTM

**Review by dilpreetsio — APPROVED** [review]

**Pull request merged**
