### PR TITLE
Added a default footer, which is used by every fossasia site

### LINKED ISSUE #18: Add footer
Add a standard FOSSASIA Footer.

### PR DESCRIPTION
**Pull request by 0x48piraj**
### Fixes #18 

* Added footer :+1: 
* Added fonts to load custom footer-logo(s) :+1: 

### Screenshot of the change : 
image

**Preview Link :** https://0x48piraj.github.io/2014.fossasia.org/

### CODE REVIEW

**Comment by 0x48piraj** [comment]
@isuruAb @ParthS007 Ping :+1:

**Review by ParthS007 — CHANGES_REQUESTED** [review]
@0x48piraj  Please adjust the footer according to the site and make it look similar to present UI, you can see that It is looking very different from whole UI of site.

**Review by NaviRocker — CHANGES_REQUESTED** [review]
@0x48piraj Try to finish it as soon as possible.

**Review by samyakbvs — CHANGES_REQUESTED** [review]
The footer vanishes as the site hits tab size, A responsive footer would be better 
screen shot 2017-12-26 at 9 23 49 pm

**Review by samyakbvs — COMMENTED** [review]
Resolve the conflicts

**Comment by duttaditya18** [comment]
Already been added.

**Comment by nzec** [comment]
@0x48piraj What is the status? Can I work on this?

**Comment by 0x48piraj** [comment]
@duttaditya18 
I already have completed the issue, but @ParthS007 said we should integrate this with a better UI.
So, I am re-working the whole website's UI.
If you like, we can collaborate as I'm currently making some projects for **FOSSASIA**.

**Comment by 0x48piraj** [comment]
@ParthS007 This PR is stale now, will open a new one probably within 10 hours, Thanks for your patience. :heart:

**Comment by nzec** [comment]
@0x48piraj All right! We'll collaborate!

**Pull request closed without merging**
