### PR TITLE
Fixes: #106: Rectify design of newsletter

### LINKED ISSUE #106: Rectify design of updates section
The updates section in the site needs design enhancements
screenshot_20180106_122053

It should feature like this
screenshot_20180106_122159

### PR DESCRIPTION
**Pull request by abishekvashok**
Rectify design of newsletter section in the site.
Added neccessary styles, a js file which is used by loklak and neccessary html code.
Fixes #106

Live link to preview: https://abishekvashok.github.io/2014.fossasia.org/
Screenshots
screenshot_20180106_132041

### CODE REVIEW

**Review by akshatnitd — COMMENTED** [review]
Some other changes relating to tweets have also popped up here, please remove them :)

**Comment by abishekvashok** [comment]
@akshatnitd it is related to tweets as well as we have tweets showing up on fossasia.org under the subscribe section

**Comment by abishekvashok** [comment]
Can't you see the tweets coming in?

**Review by isuruAb — APPROVED** [review]

**Comment by akshatnitd** [comment]
@abishekvashok Okay! I thought you had made changes only for the input box.

Nice work :) LGTM :rocket:

**Comment by abishekvashok** [comment]
Thank you @isuruAb @akshatnitd

**Pull request merged**
