### PR TITLE
Added a default footer, used by every fossasia site

### LINKED ISSUE #18: Add footer
Add a standard FOSSASIA Footer.

### PR DESCRIPTION
**Pull request by 0x48piraj**
### Fixes #18 

* Added footer :+1: 
* Added fonts to load custom footer-logo(s) :+1: 

### Screenshot of the change : 
image

> Reference : https://github.com/fossasia/2014.fossasia.org/pull/19

### CODE REVIEW

**Review by ParthS007 — CHANGES_REQUESTED** [review]
Please provide a preview link .

**Review by isuruAb — COMMENTED** [review]
please provide a preview link

**Comment by nzec** [comment]
@isuruAb @ParthS007 https://0x48piraj.github.io/2014.fossasia.org/

**Comment by 0x48piraj** [comment]
The problem is, my changes are not reflected in `gh-pages`.
I have explained it in @fossasia gitter channel.
It's a weird bug, I think. After some days, the changes will appear. :worried:

**Review by ParthS007 — CHANGES_REQUESTED** [review]
@0x48piraj  there is no footer I think.
image

**Comment by 0x48piraj** [comment]
@ParthS007 It's a weird bug!
Last time same happened, so I deployed on other server, remember ?

**Comment by akshatnitd** [comment]
@0x48piraj It is not a bug! It is due to mixed content issues. Please resolve it :)
screenshot from 2017-12-18 14-27-59

**Review by akshatnitd — CHANGES_REQUESTED** [review]
Please resolve mixed content issues

**Comment by 0x48piraj** [comment]
@akshatnitd Thank you so much. 

> Preview : https://0x48piraj.github.io/2014.fossasia.org/

**Comment by 0x48piraj** [comment]
Closing :-1:

**Pull request closed without merging**
