### PR TITLE
Fixes #123 : Lazy Load added

### LINKED ISSUE #123: Implementing Lazy Load
Load website's images when user reaches the destination
- Increases speed
- Reduces Page Load time
- Increases Page Rank

### PR DESCRIPTION
**Pull request by YashKumarVerma**
# Fixes #123 
- Pages load faster 🔥 
- Requests on page load decreased
- Website performance increased.

Preview 👍 
http://enchanting-truck.surge.sh/

### CODE REVIEW

**Review by akshatnitd — COMMENTED** [review]
Please provide a preview link

**Comment by YashKumarVerma** [comment]
@akshatnitd @ParthS007 @anshumanv 
http://enchanting-truck.surge.sh/

**Review by 0x48piraj — CHANGES_REQUESTED** [review]
Lazy Load is good, but adding `data-src` sometimes leads to a disaster, like we saw when you did the changes to our GCI website, **Whole images were broken.**

**Comment by YashKumarVerma** [comment]
That was because of attribute being data-data-src. That causes the issue. And as far as i remember, it was solved in minutes. 😃
@0x48piraj that's what google codein is all about. We learn. 😃

**Comment by YashKumarVerma** [comment]
Adding it has never caused any disaster. (at least with me).
Provided that you don't change the src of script tags 😂

**Comment by 0x48piraj** [comment]
You know it causes some chrome browsers to crash when loading `data-src` tags?

**Comment by YashKumarVerma** [comment]
Never faced anything till date whenever i implemented it. 😄 🔥

**Review by akshatnitd — COMMENTED** [review]
The preview link is not working for me and I can see a lot of console errors.

**Comment by akshatnitd** [comment]
screenshot from 2018-01-14 00-44-09

**Comment by 0x48piraj** [comment]
That's what I was talking about, Thanks for pointing them @akshatnitd :+1:

**Pull request closed without merging**
