### PR TITLE
Fixes #18 and #47 : Added Footer with @0x48piraj

### LINKED ISSUE #18: Add footer
Add a standard FOSSASIA Footer.

### LINKED ISSUE #47: Footer
There is no footer we have add one
I am working on it pls take my permission before working on the issue

### PR DESCRIPTION
**Pull request by nzec**
* Added Footer
* Me and @0x48piraj worked together to do all this. The contributions made by us are equal.  🚀 
* Fixes #18 
* Fixes #47 

***Preview Link : https://duttaditya18.github.io/2014.fossasia.org/***

---
😄

### CODE REVIEW

**Review by akshatnitd — COMMENTED** [review]
The footer looks great. But, isn't responsive. Can you check that ?

**Comment by 0x48piraj** [comment]
@akshatnitd 
It's responsive I guess, I mean all the links are working and it's not floating.
2014_footer_gif

**Comment by akshatnitd** [comment]
@0x48piraj It looks like this on my mobile.

Try to fix the overlap issue.

screenshot_20171230-180350

**Comment by 0x48piraj** [comment]
I think, It's an seperate issue for compatibility which was opened by **mario**.

**Comment by nzec** [comment]
@akshatnitd I will make a new issue for making the responsive. Can you please squash and merge?

**Comment by nzec** [comment]
@akshatnitd Made a new PR here : #81

**Pull request closed without merging**
