### PR TITLE
Added Footer!

### LINKED ISSUE #18: Add footer
Add a standard FOSSASIA Footer.

### PR DESCRIPTION
**Pull request by 0x48piraj**
### Fixes #18 

* Added footer :+1: 
* Added fonts to load custom footer-logo(s) :+1: 

### Screenshot of the change : 
image

### CODE REVIEW

**Review by isuruAb — COMMENTED** [review]
Hello @0x48piraj ,could you please provide a preview link ? then reviewers can review it easily. 
cheers !

**Comment by 0x48piraj** [comment]
@isuruAb 
### Preview : https://modest-benz-2f7827.netlify.com

> Learning to deploy jekyll everywhere! :wink:

**Comment by kol4k** [comment]
screenshot_20171206_050220
Can you make this responsive?

**Comment by 0x48piraj** [comment]
@kol4k 
It's fully responsive in web-based browsers.
Seems like, we have to add a issue like https://github.com/fossasia/2012.fossasia.org/issues/11
Cheers!

**Comment by the-codingninja** [comment]
@0x48piraj as it is a advanced task you can make the footer responsive cheers

**Comment by 0x48piraj** [comment]
Got it! :100:

**Comment by 0x48piraj** [comment]
Got to know about css a lot! Thanks @ms10398 for helping and giving me resources to learn :heart: 

---
@kol4k @isuruAb Can check now at https://0x48piraj.github.io/2012.fossasia.org/

**Review by the-codingninja — APPROVED** [review]
LGTM!!
Footer is now responsive
Great Work!!

**Comment by mariobehling** [comment]
Please make the footer full width.

**Review by anshumanv — APPROVED** [review]

**Review by isuruAb — COMMENTED** [review]
@0x48piraj  please resolve conflicts

**Review by anshumanv — APPROVED** [review]

**Comment by anshumanv** [comment]
Please resolve conflicts then this should be fine.

**Comment by akshatnitd** [comment]
@0x48piraj Please resolve the conflicts

**Review by nzec — APPROVED** [review]

**Review by the-codingninja — CHANGES_REQUESTED** [review]
Please resolve the conflicts

**Comment by 0x48piraj** [comment]
Closing this PR, and re-opening a new one as there are way to many conflicts!

**Pull request closed without merging**
