### PR TITLE
CSS and JS Minified : fixes #74

### LINKED ISSUE #74: The site should use minified css and js
Since its almost in static condition now, a minified version should be used. With the origin / expanded version still saved in Repo but not linked to the site.

Will work on it

### PR DESCRIPTION
**Pull request by YashKumarVerma**
- The css file is minified
- The JS is minified
- Original styling saved in separate file
- original script saved in separate file
Fixes #74

### CODE REVIEW

**Comment by codedsun** [comment]
@YashKumarVerma  Resolve conflicts!

**Review by isuruAb — COMMENTED** [review]
please resolve conflicts

**Comment by YashKumarVerma** [comment]
opened another PR.
😞 . Sorry

#80

**Comment by YashKumarVerma** [comment]
or if we want, we can continue with this one only ?

**Pull request closed without merging**
