### PR TITLE
Tabulation

### LINKED ISSUE #15: Proper spacing, Tabulation & adjusting fonts
> As the site is not looking good.

image

**Want to work on this issue ?**
### Yes!!

### LINKED ISSUE #16: Adapt colors and design to FOSSASIA standard
The site uses green colors and areas have a number of issues. Please adapt colors and design of the site to use the FOSSASIA standard design.

### PR DESCRIPTION
**Pull request by NaviRocker**
Fixes #15 
Fixes #16 (Link Color Green to Red)

### CODE REVIEW

**Comment by NaviRocker** [comment]
pic
pic2

**Comment by anshumanv** [comment]
Please see if it is possible to provide a test link for the changes.

**Comment by NaviRocker** [comment]
http://naveenrocker.tk/2014/

**Review by anshumanv — APPROVED** [review]

**Comment by anshumanv** [comment]
Thanks. :+1:

**Comment by anshumanv** [comment]
Please squash your commits from next time.

**Comment by mariobehling** [comment]
This does not make the site look more closely to http://fossasia.org Have to revert it.

**Comment by anshumanv** [comment]
@mariobehling thanks for following, I'll be more cautious with reviews and pushing, also I'll try to gather feedback from more people. :+1:

**Pull request merged**
