### PR TITLE
Fixes #61 : Improved responsiveness of footer

### LINKED ISSUE #61: Responsiveness
Fix the responsiveness of the site, the site becomes a bit haywire after hitting tablet size
I am working on it

### PR DESCRIPTION
**Pull request by Tanuj9043**
Fixed the responsiveness of footer.

Preview :- 
new
newer

Link :- 
https://tanuj9043.github.io/2014.fossasia.org/

### CODE REVIEW

**Review by akshatnitd — COMMENTED** [review]
Please check the gif and try to fix it. There shouldn't be any horizontal overflow.

**Comment by akshatnitd** [comment]
peek 2018-01-18 22-23

**Comment by Tanuj9043** [comment]
@akshatnitd Could you tell the device and screen size at which its happening?

**Comment by akshatnitd** [comment]
@Tanuj9043 It works fine now. Did you make any changes ?

**Comment by Tanuj9043** [comment]
No. I didn't make any changes. It was working fine. Thanks for reviewing.

**Review by isuruAb — APPROVED** [review]
but still it doesn't work correctly on smaller screen sizes

**Comment by Tanuj9043** [comment]
@isuruAb Could you please tell the screen size?

**Comment by isuruAb** [comment]
@Tanuj9043  please check the 240px width  and please refer https://fossasia.org/

**Comment by Tanuj9043** [comment]
@isuruAb I have made the changes. Please review. It seems like the schedule table was creating the problem.

Link :-
https://tanuj9043.github.io/2014.fossasia.org/

**Review by akshatnitd — APPROVED** [review]

**Pull request merged**
