### PR TITLE
Adds FOSSASIA style header and rectifies design

### LINKED ISSUE #93: Rectify design by adding fossasia style header
Currently the 2014 summit site looks awkward

screenshot_20180102_205542

It lacks:
- Proper header in fossasia format
- bad font-family
- slide at the front page is not proper and buttons overlap the text.
- fossasia lava theme.

Adding proper head elements and header will solve the issue

### PR DESCRIPTION
**Pull request by abishekvashok**
Adds FOSSASIA style header and rectifies design to make the site look
more like other summit pages. Adds FOSSASIA style header along with
needy images, fonts, javascript etc.

Fixes #93 

Live preview: https://abishekvashok.github.io/2014.fossasia.org/

screenshot_20180103_163031
screenshot_20180103_163046

### CODE REVIEW

**Comment by harshit98** [comment]
Awesome work~ @abishekvashok 

Please check these two bugs:

- When I highlight the header area: this is what it looks like:



Can you remove the text?

- Dropdown menu: Extra space at the end of dropdown menu:

**Comment by abishekvashok** [comment]
@harshit98 I did'nt modify the first one, however I am fixing it...

**Comment by abishekvashok** [comment]
@harshit98 thanks for the review. Done as you suggested:
screenshot_20180103_182032

**Review by harshit98 — APPROVED** [review]
Good work @abishekvashok 💯  🎉

**Pull request merged**
