### PR TITLE
Fixess #101: fixes intendation in 404.html

### LINKED ISSUE #101: Fix intendation of 404.html
Currently the 404.html file lacks proper intendation. Intending it as part of GCI

### PR DESCRIPTION
**Pull request by abishekvashok**
Fixes intendation issues in 404.html by adding proper whitepaces,
replacing tabs with spaces, removing trailing tabs and whitespaces.
Also closes an existing div which was not closed.

Fixes #101

### CODE REVIEW

**Review by ParthS007 — APPROVED** [review]

**Review by vaibhavsingh97 — APPROVED** [review]

**Review by vaibhavsingh97 — CHANGES_REQUESTED** [review]
Please follow best practices, your PR title should be `Fixes #<issue-number>: <message>`

**Review by nzec — APPROVED** [review]
Looks good!

**Comment by abishekvashok** [comment]
@vaibhavsingh97 done

**Review by harshit98 — APPROVED** [review]

**Comment by abishekvashok** [comment]
Thank you

**Pull request merged**
