### PR TITLE
Fixed #36: Added social links

### LINKED ISSUE #36: Social links need to be added
I am working on this issue

### PR DESCRIPTION
**Pull request by samyakbvs**

### CODE REVIEW

**Comment by samyakbvs** [comment]
#36

**Comment by samyakbvs** [comment]
https://samyakbvs.github.io/samya-k-jainbvs-2014.fossasia.org/

**Review by nzec — CHANGES_REQUESTED** [review]
Does not look too nice.

**Review by akshatnitd — CHANGES_REQUESTED** [review]
You should look to do something better in terms of design. The current PR that you've proposed doesn't look that good.

**Comment by samyakbvs** [comment]
Okay

**Comment by samyakbvs** [comment]
From where should I take the icons @akshatnitd

**Comment by samyakbvs** [comment]
I hope now its fine I have added the icons

**Review by abishekvashok — CHANGES_REQUESTED** [review]
Pls give the working deployment link

**Review by akshatnitd — COMMENTED** [review]
Please provide demo link, so that we can review!

**Comment by samyakbvs** [comment]
https://samyakbvs.github.io/s-a-m-y-a-k-jainbvs-2014.fossasia.org/

**Comment by samyakbvs** [comment]
@akshatnitd

**Comment by harshit98** [comment]
@samyakbvs 

- Use `Fixes #(issue-no): details of fix`.
- Change the color of icons to black. It will look nice.
- Increase the size of icons similar to on fossasia.org website.

**Comment by harshit98** [comment]
@samyakbvs You have not increased the size of icon.

**Review by 0x48piraj — CHANGES_REQUESTED** [review]
Squash the commits :+1:

**Review by mariobehling — CHANGES_REQUESTED** [review]
Please add social links in the same way as on FOSSASIA main site in the footer.

**Comment by samyakbvs** [comment]
OKay wait I will

**Pull request closed without merging**
