### PR TITLE
Fixes Issue #39. Added more content

### PR DESCRIPTION
**Pull request by arjunpandey2003**
Issue #39
Added more content in about page

### CODE REVIEW

**Comment by arjunpandey2003** [comment]
@gabru-md check this out

**Comment by arjunpandey2003** [comment]
Sorry for earlier confusion

**Comment by gabru-md** [comment]
@arjunpandey2003 It is okay to make mistakes but it is always important to learn from them.
This is good!

**Review by gabru-md — APPROVED** [review]
Thanks for the content

**Comment by arjunpandey2003** [comment]
Thanks!

**Comment by arjunpandey2003** [comment]
@gabru-md you are very helpful, thank you!

**Comment by the-codingninja** [comment]
Can you please change the PR name `Fixes #(issue-num): details of fix`
Now you should follow Best Practices as much you can

**Review by harshit98 — APPROVED** [review]

**Comment by arjunpandey2003** [comment]
@harshit98 can you also approve my task

**Comment by arjunpandey2003** [comment]
Thanks!

**Pull request merged**
