### PR TITLE
Theme Color Red 

### LINKED ISSUE #16: Adapt colors and design to FOSSASIA standard
The site uses green colors and areas have a number of issues. Please adapt colors and design of the site to use the FOSSASIA standard design.

### PR DESCRIPTION
**Pull request by NaviRocker**
Added Red Color to the Header and Sidebar Fixes #16

### CODE REVIEW

**Comment by NaviRocker** [comment]
Preview Link - https://naveentherocker.github.io/2014.fossasia.org/

**Comment by mariobehling** [comment]
This change is not suitable. Please start by improving top bar and footer.

**Comment by NaviRocker** [comment]
What kind of Top Bar do you want sir?
A Transparent Header like in fossasia.org?

**Comment by anshumanv** [comment]
Yes, @naveentherocker as close to https://fossasia.org/ as possible.

**Comment by NaviRocker** [comment]
Sure!

**Pull request closed without merging**
