### PR TITLE
Fixed #61 && #58: Padding and Design

### LINKED ISSUE #61: Responsiveness
Fix the responsiveness of the site, the site becomes a bit haywire after hitting tablet size
I am working on it

### PR DESCRIPTION
**Pull request by samyakbvs**
Removed blank spaces and added padding where required

### CODE REVIEW

**Comment by samyakbvs** [comment]
Will provide the test link shortly

**Comment by samyakbvs** [comment]
https://samyakbvs.github.io/lalala-2014.fossasia.org/

**Comment by samyakbvs** [comment]
Here's the link but...
screen shot 2017-12-28 at 10 11 11 pm
But as you can see in the right sidebar the changes I have made aren't implemented in the test link. For example, the height that is 285 em I removed that in my forked repo but it is still there in test site

**Comment by samyakbvs** [comment]
What's the reason behind this?

**Comment by samyakbvs** [comment]
screen shot 2017-12-28 at 10 14 42 pm
Its same case if I deploy it according to readme.md

**Comment by vaibhavsingh97** [comment]
Please always add reference to issues in PR messages with Fixes, closes, solves, keywords. Thanks

**Comment by vaibhavsingh97** [comment]
Can you please share screenshot where your changes will be reflected

**Comment by samyakbvs** [comment]
Yes

**Comment by samyakbvs** [comment]
Before:
screen shot 2017-12-29 at 12 45 57 am

After:



I hope they are sufficient :)

**Comment by samyakbvs** [comment]
Before:
screen shot 2017-12-28 at 10 11 11 pm

After:
screen shot 2017-12-29 at 12 44 08 am
screen shot 2017-12-29 at 12 44 55 am

**Comment by samyakbvs** [comment]
Before: 
screen shot 2017-12-29 at 12 52 44 am

**Review by vaibhavsingh97 — CHANGES_REQUESTED** [review]
Use media queries instead. This is just a workaround

**Comment by samyakbvs** [comment]
I can't understand how to implement the links

**Pull request closed without merging**
