### PR TITLE
css and js minified : fixes #74

### LINKED ISSUE #74: The site should use minified css and js
Since its almost in static condition now, a minified version should be used. With the origin / expanded version still saved in Repo but not linked to the site.

Will work on it

### PR DESCRIPTION
**Pull request by YashKumarVerma**
- The css file is minified
- The JS is minified
- Original styling saved in separate file
- original script saved in separate file
Fixes #74

### CODE REVIEW

**Review by nzec — APPROVED** [review]
Awesome! I think you should change add .min to the names of the minified files and then link the minified files to the header. It is not needed however!

🚀 Awesome work!

**Comment by harshit98** [comment]
@YashKumarVerma 

- Provide deployment link to review changes.
- @duttaditya18 suggestion is quite good. You should do the suggested change.

**Review by isuruAb — COMMENTED** [review]
please add a demo link.

**Comment by duttaditya18** [comment]
@harshit98 @isuruAb Why is a demo link required? He only minified the stuff. 

Anyway here is the preview link : https://yashkumarverma.github.io/gci17.fossasia.org/

**Comment by shashwat1002** [comment]
There are merge conflicts though, resolve them and that should work

**Comment by shashwat1002** [comment]
@harshit98 @isuruAb @duttaditya18 the preview link is https://yashkumarverma.github.io/2014.fossasia.org/

**Comment by YashKumarVerma** [comment]
Hello there Everyone. Is this me or anyone else can also not find the `style.css` linked to any of the file.

**Comment by YashKumarVerma** [comment]
https://github.com/fossasia/2014.fossasia.org/search?q=style.css&type=Code&utf8=%E2%9C%93

**Comment by YashKumarVerma** [comment]
@isuruAb @harshit98 @shashwat1002

**Comment by nzec** [comment]
@YashKumarVerma Why did you do the changes in the _site folder?

**Comment by YashKumarVerma** [comment]
um, that's the only place we have a `.css` file. (if i'm not wrong)

**Comment by nzec** [comment]
@YashKumarVerma The `.css` is there in `_includes/header.html`. Any changes make in _site will not be visible.

**Comment by YashKumarVerma** [comment]
looks like there isn't. 😕 
https://github.com/fossasia/2014.fossasia.org/blob/gh-pages/_includes/header.html

**Comment by nzec** [comment]
@YashKumarVerma The css is present in header.html. There is no extra CSS file.

**Comment by nzec** [comment]
Try it yourself. If you make any changes in the _site folder, the changes will not be visible in the Github Pages Website.

**Comment by YashKumarVerma** [comment]
so shall i minify that css ? then it'd be diffcicult to edit the same in the future

**Comment by nzec** [comment]
@yash You're right. Ask the mentors. I think we must work on separating the css into its own file.

**Comment by YashKumarVerma** [comment]
or shall i do the same ?

**Comment by shashwat1002** [comment]
Try making a .css file in the _includes folder and linking in the header.html(and wherever else required), I believe that should work.

**Comment by shashwat1002** [comment]
I don't think you should make a different CSS file because say you do make one in the _includes folder and link to it in  header.html jekyll will simply put the html of header.html and then the directory won't be found.

**Comment by YashKumarVerma** [comment]
Then what am isupposed to do?

**Pull request closed without merging**
