### PR TITLE
Changed fonts

### PR DESCRIPTION
**Pull request by arjunpandey2003**
Fixes issue #44 
Updated style.css
Updated about.html

### CODE REVIEW

**Review by anshumanv — COMMENTED** [review]
Please provide a test link and squash your commits.

**Comment by arjunpandey2003** [comment]
@anshumanv there is some problem with my preview links its not showing my changes

**Comment by arjunpandey2003** [comment]
https://arjunpandey2003.github.io/2014.fossasiarjunp.org/about.html

**Comment by anshumanv** [comment]
You can send screenshots of change in that case.

**Comment by arjunpandey2003** [comment]
Screenshots of ?

**Comment by arjunpandey2003** [comment]
@anshumanv screenshots of?
Should i serve the page using jekyll

**Comment by anshumanv** [comment]
Screenshots of the change when you made changes and tested it locally.

**Comment by arjunpandey2003** [comment]
https://user-images.githubusercontent.com/25302509/34356226-2533ca1a-ea62-11e7-8615-d9c2c3e5d407.png

**Comment by arjunpandey2003** [comment]
Squashing commits

**Review by anshumanv — APPROVED** [review]
Seems fine from the screenshot.

**Comment by arjunpandey2003** [comment]
@anshumanv thanks

**Review by isuruAb — APPROVED** [review]

**Pull request merged**
