### PR TITLE
fix table agenda

### PR DESCRIPTION
**Pull request by kol4k**
24650655_826657120850153_320000621_o 1

### CODE REVIEW

**Comment by mariobehling** [comment]
Please also fix heading markup issue. If possible please provide a test link. Cheers.

**Comment by kol4k** [comment]
I don't have hosting for provide this code.

**Comment by mariobehling** [comment]
You can use https://pages.github.com, which is available through your own repo.

**Review by 0x48piraj — COMMENTED** [review]
Looks good!

**Comment by akshatnitd** [comment]
Can you please post a demo link

**Comment by akshatnitd** [comment]
@kol4k I have tested it separately. LGTM :) 

Try to give a demo link from the next time, so that it becomes easier for the reviewers.

Merging :rocket:

**Comment by akshatnitd** [comment]
@kol4k I just noticed that you had made changes only in the _site folder. You need to make similar changes in the .md files as well. For eg : ```saturday.md```

Make sure to follow this pattern in next commits.

**Pull request merged**
