### PR TITLE
Flickr does not belong in the 'external' dropdown menu :D

### PR DESCRIPTION
**Pull request by yashk0thari**
The flickr link is anyways given in the hamburger; having it in two places; that to really close to each other seems unnecessary :D

Update header.html

### CODE REVIEW

**Comment by yashk0thari** [comment]
https://beta-king.github.io/lovate.2014.fossasia.org/ --> Preview Link :D

**Review by abishekvashok — APPROVED** [review]
I guess flickr was there to provide pictures of the summit, but if you want to remove it then let's remove it :)

**Comment by yashk0thari** [comment]
Ik but pictures can and are provided in the hamburger link aswell :D

**Review by nzec — CHANGES_REQUESTED** [review]
Unnecessary change. Don't see a point.

**Comment by yashk0thari** [comment]
The point is that the link is provided in two different location in the same area which is unnecessary, thats why the PR to remove it :D

**Review by nzec — APPROVED** [review]
All right. Cool!

**Comment by yashk0thari** [comment]
yeah, although i maybe wrong :D lets let the mentors decide :D

**Review by harshit98 — APPROVED** [review]

**Pull request merged**
