### PR TITLE
Fixes #63 : Added more social links

### LINKED ISSUE #63: Needs more social links & icons
# Missing social links in footer
# I have added them

### PR DESCRIPTION
**Pull request by saarthakchats**
Fixes #63 : Added more social links
# Footer needs more social links
# Things done
### Added VK, YouTube, G+, Flickr, Linkedin
[Deploy Link](https://saarthakchats.github.io/dhooter/)

### CODE REVIEW

**Review by ParthS007 — CHANGES_REQUESTED** [review]
Please have a chat with  @0x48piraj  as he have a pending PR of adding footer just like other fossasia sites, after that only these link can be added, at present It looks very weird at bottom

**Comment by nzec** [comment]
@saarthakchats Yes. Let @0x48piraj add the footer and then add extra social links.

**Comment by saarthakchats** [comment]
ok

**Review by isuruAb — COMMENTED** [review]
please resolve conflicts

**Review by akshatnitd — COMMENTED** [review]
Please resolve the conflicts!

**Comment by harshit98** [comment]
@saarthakchats Resolve conflicts so that I can merge the PR.

**Review by realslimshanky — CHANGES_REQUESTED** [review]
Please remove conflicts.

**Review by 0x48piraj — COMMENTED** [review]
I have implemented the footer :+1:

**Comment by saarthakchats** [comment]
I will add in another PR

**Pull request closed without merging**
