### PR TITLE
Fixes #108 : Codebase Formatted

### LINKED ISSUE #108: Code Base not uniformly formatted
The entire source code should be formatted so that editing / working on the same becomes easy.

### PR DESCRIPTION
**Pull request by YashKumarVerma**
The entire source code follows a uniform indentation, `css` and `js` files are ***beautified*** too.
image
Fixes #108

### CODE REVIEW

**Review by ParthS007 — COMMENTED** [review]
@YashKumarVerma  Please resolve conflicts.

**Review by isuruAb — COMMENTED** [review]
please resolve conflicts

**Comment by YashKumarVerma** [comment]
@ParthS007 @isuruAb willbe doing the same in 8 hours from now.

**Comment by YashKumarVerma** [comment]
Please do not ask me to squash the commits.
I don'tknow why but the commit is just invisible from the squash screen but visible in logs
image
image

**Comment by YashKumarVerma** [comment]
@ParthS007 @isuruAb

**Review by ParthS007 — APPROVED** [review]

**Review by isuruAb — APPROVED** [review]

**Pull request merged**
