### PR TITLE
Fixes #118,#128 Removed image and applied icon

### LINKED ISSUE #118: Broken Github Icon
The Github icon is not showing up.

### LINKED ISSUE #121: Icons not matching FOSSASIA's red color
image

### PR DESCRIPTION
**Pull request by YashKumarVerma**
There is a image between other **icons**
image

Fixes #118,#128 
Link https://yashkumarverma.github.io/2014.fossasia.org

### CODE REVIEW

**Comment by YashKumarVerma** [comment]
@ms10398

**Review by akshatnitd — CHANGES_REQUESTED** [review]
The hover color change doesn't work on the github button. You need to add some more CSS for it.

**Comment by YashKumarVerma** [comment]
the github icon is a image. what can we do to change it's color to red ?

**Comment by YashKumarVerma** [comment]
@akshatnitd

**Review by 0x48piraj — COMMENTED** [review]
Why red ?

**Comment by YashKumarVerma** [comment]
@0x48piraj cause that's the color the hyperlinks change to, on hover.

**Comment by 0x48piraj** [comment]
That will open up issues in each and every summit website, Please ask **Mario** before doing the changes !

**Comment by YashKumarVerma** [comment]
@mariobehling Can we have the `fossasia red` color on icon hover ?

**Review by akshatnitd — COMMENTED** [review]
There is no color change on hover now.

**Comment by YashKumarVerma** [comment]
@akshatnitd ,
as the other community sites don't have that, i removed it. 
So PR now replaces an image with icon.

**Review by akshatnitd — APPROVED** [review]

**Review by anshumanv — APPROVED** [review]

**Pull request merged**
