### PR TITLE
Fixed #75: Table

### LINKED ISSUE #75: Table
Th agenda table should have a border 
I am working on it

### PR DESCRIPTION
**Pull request by samyakbvs**
#75 
Added a table to the Agenda section

### CODE REVIEW

**Comment by samyakbvs** [comment]
https://samyakbvs.github.io/dodo-2014.fossasia.org/

**Comment by samyakbvs** [comment]
Made the link but the changes aren't showing up, they always don't in 2014.fossasia.org repo
screen shot 2017-12-30 at 2 21 59 am
Tried deploying locally but the changes don't show up, they always don't in 2014.fossasia.org repo
screen shot 2017-12-30 at 2 19 23 am
But I have a screenshot of how the Section will look after merging
screen shot 2017-12-30 at 2 11 37 am

**Comment by shashwat1002** [comment]
To see the changes on your git hub pages link, you can go to _config.yml and change the value for "url:" to  https://samyakbvs.github.io/dodo-2014.fossasia.org/ though do change it to http://fossasia.github.io/2014.fossasia.org/ before sending in the pull request.

**Comment by vaibhavsingh97** [comment]
@samyakbvs Your fork doesn't contain changes that's why it's not showing any changes in the link

**Review by anshumanv — COMMENTED** [review]
Looks fine from the screenshot, please try to make the link work anyways.

**Review by isuruAb — COMMENTED** [review]
please resolve conflicts

**Comment by vaibhavsingh97** [comment]
Please resolve conflicts

**Review by nzec — CHANGES_REQUESTED** [review]
I don't think the border is required.

**Comment by samyakbvs** [comment]
I think it is

**Comment by samyakbvs** [comment]
Closing this and then re-opening

**Comment by nzec** [comment]
@samyakbvs Cool! 👍

**Pull request closed without merging**
